### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by mschoch** [mschoch/fireproof-netlify-extension-demo#1]
We had verified that this was working across browsers in the past.  However, today I went back, and in Chrome I get the following:

```
index-CMD2JqZg.js:185 Uncaught (in promise) Error: CBOR decode error: did not find any content to decode
    at decodeFirst (index-CMD2JqZg.js:185:52681)
    at decode$b (index-CMD2JqZg.js:185:52884)
    at BlockIvKeyIdCodec.decode (index-CMD2JqZg.js:188:35465)
    at decode$1 (index-CMD2JqZg.js:187:26118)
    at Loader$1.makeDecoderAndCarReader (index-CMD2JqZg.js:187:47505)
    at async Loader$1.loadCar (index-CMD2JqZg.js:187:46925)
```

Nothing new was deployed.  According to Netlify, this site was last deployed on Nov 25 at 1:04pm.

This app uses the following versions:

```
"@fireproof/core": "0.19.99",
"@fireproof/netlify": "0.19.99"
```

I have tried nuking the indexdbs, but it has no effect.

**Comment by jchris** [comment]
I tried it again and it works, maybe was a deploy env issue, they did a change there. https://test-extensio-app.netlify.app works
